export const PROJECTS = [
  {
    id: 1,
    country: 'Australia',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non elit dui. Nullam vel eros sit amet arcu vestibulum accumsan in in leo.',
    pathway: 'Coastal Wetland',
    action: 'Protect',
    phase: 'Early stage',
    categories: ['Community-based', 'Carbon Project', 'Policy Project'],
    area: '2,000 ha',
    people: '6,000',
    mitigation: '1,000,000 tCO2e',
    co_benefits: ['Biodiversity', 'Water quality', 'Livelihoods'],
    image: 'https://dummyimage.com/330x290/000/fff&text=+',
  },
  {
    id: 2,
    country: 'Angola',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non elit dui. Nullam vel eros sit amet arcu vestibulum accumsan in in leo.',
    pathway: 'Coastal Wetland',
    action: 'Protect',
    phase: 'Early stage',
    categories: ['Community-based', 'carbon-project', 'policy-project'],
    area: '2,000 ha',
    people: '6,000',
    mitigation: '1,000,000 tCO2e',
    co_benefits: ['Biodiversity', 'Water quality', 'Livelihoods'],
    image: 'https://dummyimage.com/330x290/000/fff&text=+',
  },
  {
    id: 3,
    country: 'Brazil',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non elit dui. Nullam vel eros sit amet arcu vestibulum accumsan in in leo.',
    pathway: 'Coastal Wetland',
    action: 'Protect',
    phase: 'Early stage',
    categories: ['Community-based', 'carbon-project', 'policy-project'],
    area: '2,000 ha',
    people: '6,000',
    mitigation: '1,000,000 tCO2e',
    co_benefits: ['Biodiversity', 'Water quality', 'Livelihoods'],
    image: 'https://dummyimage.com/330x290/000/fff&text=+',
  },
  {
    id: 4,
    country: 'Kenia',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non elit dui. Nullam vel eros sit amet arcu vestibulum accumsan in in leo.',
    pathway: 'Coastal Wetland',
    action: 'Protect',
    phase: 'Early stage',
    categories: ['Community-based', 'carbon-project', 'policy-project'],
    area: '2,000 ha',
    people: '6,000',
    mitigation: '1,000,000 tCO2e',
    co_benefits: ['Biodiversity', 'Water quality', 'Livelihoods'],
    image: 'https://dummyimage.com/330x290/000/fff&text=+',
  },
  {
    id: 5,
    country: 'Tanzania',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non elit dui. Nullam vel eros sit amet arcu vestibulum accumsan in in leo.',
    pathway: 'Coastal Wetland',
    action: 'Protect',
    phase: 'Early stage',
    categories: ['Community-based', 'carbon-project', 'policy-project'],
    area: '2,000 ha',
    people: '6,000',
    mitigation: '1,000,000 tCO2e',
    co_benefits: ['Biodiversity', 'Water quality', 'Livelihoods'],
    image: 'https://dummyimage.com/330x290/000/fff&text=+',
  },
  {
    id: 6,
    country: 'Costa Rica',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non elit dui. Nullam vel eros sit amet arcu vestibulum accumsan in in leo.',
    pathway: 'Coastal Wetland',
    action: 'Protect',
    phase: 'Early stage',
    categories: ['Community-based', 'carbon-project', 'policy-project'],
    area: '2,000 ha',
    people: '6,000',
    mitigation: '1,000,000 tCO2e',
    co_benefits: ['Biodiversity', 'Water quality', 'Livelihoods'],
    image: 'https://dummyimage.com/330x290/000/fff&text=+',
  },
];
